apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-dotnet-api
  labels:
    app: dotnet-api
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: {{ .Values.service.protocol }}
  selector:
    app: dotnet-api
    release: {{ .Release.Name }}