replicaCount: 2

image:
  repository: mizanussayed/dotnet-api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000
  targetPort: 8000
  protocol: TCP

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi